CREATE TABLE APPLE_MEMBER(
    TNO NUMBER PRIMARY KEY,
    TNAME VARCHAR2(100) NOT NULL,
    TPOINT NUMBER NOT NULL,
    TDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_TNO START WITH 1 INCREMENT BY 1 NOCACHE;

SELECT * FROM APPLE_MEMBER;